# Generated by Django 5.0.7 on 2024-10-17 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminId', models.CharField(max_length=100)),
                ('adminBranch', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SuperAdminApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_applicationId', models.CharField(max_length=100)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='superadmin', to='AdminApp1.superadmin')),
            ],
        ),
    ]
