# Generated by Django 5.0.7 on 2024-11-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp1', '0003_alter_dsamasterdata_masterdataimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsMasterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MasterDataImage', models.FileField(upload_to='Accounts/MasterData/')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FranchiseMasterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MasterDataImage', models.FileField(upload_to='Franchise/MasterData/')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='dsamasterdata',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
