# Generated by Django 5.0.7 on 2024-11-10 07:08

import SmAdmin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='franchise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('franchise_id', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('pan', models.CharField(blank=True, max_length=12, null=True)),
                ('aadhar', models.CharField(max_length=12)),
                ('profession', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('agreeCheck', models.BooleanField(default=False)),
                ('dsaPhoto', models.ImageField(upload_to='dsa/', validators=[SmAdmin.models.validate_image_file])),
                ('aadharFront', models.ImageField(upload_to='dsa/', validators=[SmAdmin.models.validate_image_file])),
                ('aadharBack', models.ImageField(upload_to='dsa/', validators=[SmAdmin.models.validate_image_file])),
                ('panCard', models.ImageField(upload_to='dsa/', validators=[SmAdmin.models.validate_image_file])),
                ('bankDocument', models.ImageField(upload_to='dsa/', validators=[SmAdmin.models.validate_image_file])),
                ('aproval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
            ],
        ),
    ]
