# Generated by Django 5.0 on 2024-11-05 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ggg1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hrcredentials',
            name='department',
        ),
        migrations.RemoveField(
            model_name='hrcredentials',
            name='position',
        ),
    ]
